// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

type Directory struct {
	Inode  int64
	Name   string
	Parent int64
}

type File struct {
	Inode  int64
	Name   string
	Parent int64
	Data   []byte
}
